## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_version=2023.09.03

## Dependencies
biomesoplenty_version=21.1.0.13

## Mod Properties
mod_id=visceralheapfix
mod_name=Visceral Heap Fix
repo_name=VisceralHeapFix
mod_license=MIT
mod_version=2.0.1
mod_author=RedCraft86
mod_group_id=com.redcraft86.visceralheapfix
mod_description=Fixes Visceral Heap tendons from incorrectly generating when the Nether's height is increased.
mod_credits=Biomes O' Plenty by Forstride