## Dependencies
biomesoplenty_version=21.1.0.13

## Mod Properties
mod_id=visceralheapfix
mod_name=Visceral Heap Fix
repo_name=VisceralHeapFix
mod_license=MIT
mod_version=2.0.0
mod_authors=RedCraft86
mod_group_id=com.redcraft86.visceralheapfix
mod_description=Fixes Visceral Heap tendons from incorrectly generating when the Nether's height is increased.
mod_credits=Biomes O' Plenty by Forstride